In [1]:
# pandas
import pandas as pd
from pandas import Series,DataFrame

# numpy, matplotlib, seaborn
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline
matplotlib.style.use('ggplot')

# remove warnings
import warnings
warnings.filterwarnings('ignore')

# Feature engineering

In [2]:
# 读取训练集和测试集为 DataFrame
train_data = pd.read_csv('data/train.csv')
test_data = pd.read_csv('data/test.csv')

train_data.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [4]:
# 基于 Predict_Survival.ipynb 类似的操作
train_data = train_data.drop(['PassengerId', 'Ticket'], axis=1)
# train_data = train_data.drop(['Ticket'], axis=1)
test_data = test_data.drop(['Ticket'], axis=1)

In [5]:
# 获取名字中的 Title
def get_name_title(name):
    if name.find('Mr.') != -1:
        return 'Mr'
    elif name.find('Mrs.') != -1:
        return 'Mrs'
    elif name.find('Miss.') != -1:
        return 'Miss'
    elif name.find('Master.') != -1:
        return 'Master'
    elif name.find('Don.') != -1:
        return 'Don'
    elif name.find('Rev.') != -1:
        return 'Rev'
    elif name.find('Dr.') != -1:
        return 'Dr'
    elif name.find('Mme.') != -1:
        return 'Mme'
    elif name.find('Ms.') != -1:
        return 'Ms'
    elif name.find('Major.') != -1:
        return 'Major'
    elif name.find('Lady.') != -1:
        return 'Lady'
    elif name.find('Sir.') != -1:
        return 'Sir'
    elif name.find('Mlle.') != -1:
        return 'Mlle'
    elif name.find('Col.') != -1:
        return 'Col'
    elif name.find('Capt.') != -1:
        return 'Capt'
    elif name.find('Countess.') != -1:
        return 'Countess'
    elif name.find('Jonkheer.') != -1:
        return 'Jonkheer'
    else:
        return 'None'

# 添加 Title 字段
train_data['Title'] = train_data['Name'].apply(get_name_title)
train_data = train_data.drop('Name', axis=1)

test_data['Title'] = test_data['Name'].apply(get_name_title)
test_data = test_data.drop('Name', axis=1)

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Sex         891 non-null object
Age         714 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Cabin       204 non-null object
Embarked    889 non-null object
Title       891 non-null object
dtypes: float64(2), int64(4), object(4)
memory usage: 69.7+ KB


In [7]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
Title          418 non-null object
dtypes: float64(2), int64(4), object(4)
memory usage: 32.7+ KB


In [8]:
# 测试集和训练集合并
combined_train_data = train_data.drop('Survived', axis=1).append(test_data.drop('PassengerId', axis=1))
combined_train_data.reset_index(inplace=True)
combined_train_data.drop('index', axis=1, inplace=True)
combined_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 9 columns):
Pclass      1309 non-null int64
Sex         1309 non-null object
Age         1046 non-null float64
SibSp       1309 non-null int64
Parch       1309 non-null int64
Fare        1308 non-null float64
Cabin       295 non-null object
Embarked    1307 non-null object
Title       1309 non-null object
dtypes: float64(2), int64(3), object(4)
memory usage: 92.1+ KB


In [9]:
combined_train_data.head()

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked Title
0       3    male  22.0      1      0   7.2500   NaN        S    Mr
1       1  female  38.0      1      0  71.2833   C85        C   Mrs
2       3  female  26.0      0      0   7.9250   NaN        S  Miss
3       1  female  35.0      1      0  53.1000  C123        S   Mrs
4       3    male  35.0      0      0   8.0500   NaN        S    Mr

In [10]:
# Processing the ages
grouped = combined_train_data.groupby(['Sex','Pclass','Title'])
grouped.median()

Age  SibSp  Parch       Fare
Sex    Pclass Title                                  
female 1      Countess  33.0      0      0   86.50000
              Dr        49.0      0      0   25.92920
              Lady      48.0      1      0   39.60000
              Miss      30.0      0      0  108.65415
              Mlle      24.0      0      0   59.40210
              Mme       24.0      0      0   69.30000
              Mrs       45.0      1      0   78.26670
              None      39.0      0      0  108.90000
       2      Miss      20.0      0      0   20.25000
              Mrs       30.5      1      0   26.00000
              Ms        28.0      0      0   13.00000
       3      Miss      18.0      0      0    8.05000
              Mrs       31.0      1      1   15.50000
              Ms         NaN      0      0    7.75000
male   1      Capt      70.0      1      1   71.00000
              Col       54.5      0      0   32.00000
              Don       40.0      0      0   27.72080
              Dr        47.0      1      0   81.85830
              Jonkheer  38.0      0      0    0.00000
              Major     48.5      0      0   28.52500
              Master     6.0      1      2  134.50000
              Mr        41.5      0      0   47.10000
              Sir       49.0      1      0   56.92920
       2      Dr        38.5      0      0   12.25000
              Master     2.0      1      1   26.00000
              Mr        30.0      0      0   13.00000
              Rev       41.5      0      0   13.00000
       3      Master     6.0      3      1   22.35830
              Mr        26.0      0      0    7.89580

In [11]:
def fill_missed_age(row):
    if row['Sex']=='female' and row['Pclass'] == 1:
        if row['Title'] == 'Countess':
            return 33
        elif row['Title'] == 'Dr':
            return 49
        elif row['Title'] == 'Lady':
            return 48
        elif row['Title'] == 'Miss':
            return 30
        elif row['Title'] == 'Mlle':
            return 24
        elif row['Title'] == 'Mme':
            return 24
        elif row['Title'] == 'Mrs':
            return 45
        elif row['Title'] == 'None':
            return 39
    
    elif row['Sex']=='female' and row['Pclass'] == 2:
        if row['Title'] == 'Miss':
            return 20
        elif row['Title'] == 'Ms':
            return 28
        elif row['Title'] == 'Mrs':
            return 31
        
    elif row['Sex']=='female' and row['Pclass'] == 3:
        if row['Title'] == 'Miss':
            return 18
        elif row['Title'] == 'Ms':
            return 28
        elif row['Title'] == 'Mrs':
            return 31
        
    elif row['Sex']=='male' and row['Pclass'] == 1:
        if row['Title'] == 'Capt':
            return 70
        elif row['Title'] == 'Col':
            return 55
        elif row['Title'] == 'Don':
            return 40
        elif row['Title'] == 'Dr':
            return 47
        elif row['Title'] == 'Jonkheer':
            return 38
        elif row['Title'] == 'Major':
            return 49
        elif row['Title'] == 'Master':
            return 6
        elif row['Title'] == 'Mr':
            return 42
        elif row['Title'] == 'Sir':
            return 50
    
    elif row['Sex']=='male' and row['Pclass'] == 2:
        if row['Title'] == 'Dr':
            return 39
        elif row['Title'] == 'Master':
            return 2
        elif row['Title'] == 'Mr':
            return 30
        elif row['Title'] == 'Rev':
            return 42
        
    elif row['Sex']=='male' and row['Pclass'] == 3:
        if row['Title'] == 'Master':
            return 6
        elif row['Title'] == 'Mr':
            return 26
            
combined_train_data['Age'] = combined_train_data.apply(lambda row : fill_missed_age(row)
                                                      if np.isnan(row['Age']) else row['Age'],
                                                       axis=1)

In [12]:
combined_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 9 columns):
Pclass      1309 non-null int64
Sex         1309 non-null object
Age         1309 non-null float64
SibSp       1309 non-null int64
Parch       1309 non-null int64
Fare        1308 non-null float64
Cabin       295 non-null object
Embarked    1307 non-null object
Title       1309 non-null object
dtypes: float64(2), int64(3), object(4)
memory usage: 92.1+ KB


In [13]:
# Fare 票价可能和等级 Pclass 和登录的船舱 Embarked 有关
grouped = combined_train_data.groupby(['Pclass', 'Embarked', 'Sex'])
grouped_median_data = grouped.median()
grouped_median_data

Age  SibSp  Parch      Fare
Pclass Embarked Sex                                 
1      C        female  39.0      0      0  83.15830
                male    42.0      0      0  62.66875
       Q        female  35.0      1      0  90.00000
                male    44.0      2      0  90.00000
       S        female  35.0      1      0  78.85000
                male    42.0      0      0  35.50000
2      C        female  23.0      1      0  27.72080
                male    30.0      0      0  15.04580
       Q        female  25.0      0      0  12.35000
                male    57.0      0      0  12.35000
       S        female  28.0      0      0  23.00000
                male    30.0      0      0  13.00000
3      C        female  18.0      0      1  14.45420
                male    26.0      0      0   7.22920
       Q        female  18.0      0      0   7.75000
                male    26.0      0      0   7.75000
       S        female  22.0      1      0  13.77500
                male    26.0      0      0   8.05000

In [14]:
combined_train_data[combined_train_data.Fare.isnull()]

Pclass   Sex   Age  SibSp  Parch  Fare Cabin Embarked Title
1043       3  male  60.5      0      0   NaN   NaN        S    Mr

In [15]:
combined_train_data.Fare.fillna(26, inplace=True)

In [16]:
# 填充缺失的 Embarked
combined_train_data['Embarked'] = combined_train_data['Embarked'].fillna('S')

In [17]:
combined_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 9 columns):
Pclass      1309 non-null int64
Sex         1309 non-null object
Age         1309 non-null float64
SibSp       1309 non-null int64
Parch       1309 non-null int64
Fare        1309 non-null float64
Cabin       295 non-null object
Embarked    1309 non-null object
Title       1309 non-null object
dtypes: float64(2), int64(3), object(4)
memory usage: 92.1+ KB


In [18]:
combined_train_data.head()

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked Title
0       3    male  22.0      1      0   7.2500   NaN        S    Mr
1       1  female  38.0      1      0  71.2833   C85        C   Mrs
2       3  female  26.0      0      0   7.9250   NaN        S  Miss
3       1  female  35.0      1      0  53.1000  C123        S   Mrs
4       3    male  35.0      0      0   8.0500   NaN        S    Mr

In [19]:
# 处理 Cabin 字段及填补缺失的 Cabin 字段
# 缺失字段填充为 U (for Uknown)
combined_train_data.Cabin.fillna('U',inplace=True)
# 获取船舱的首字母
combined_train_data['Cabin'] = combined_train_data['Cabin'].map(lambda c : c[0])

In [20]:
# 处理 SibSp 和 Parch 字段，添加FamilySize、Singleton、SmallFamily、LargeFamily字段，保留原始字段
combined_train_data['FamilySize'] = combined_train_data['SibSp']+combined_train_data['Parch']+1

combined_train_data['Singleton'] = combined_train_data['FamilySize'].map(lambda s : 1 if s == 1 else 0)
combined_train_data['SmallFamily'] = combined_train_data['FamilySize'].map(lambda s : 1 if 2<=s<=4 else 0)
combined_train_data['LargeFamily'] = combined_train_data['FamilySize'].map(lambda s : 1 if 5<=s else 0)

In [21]:
combined_train_data.head()

Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked Title  \
0       3    male  22.0      1      0   7.2500     U        S    Mr   
1       1  female  38.0      1      0  71.2833     C        C   Mrs   
2       3  female  26.0      0      0   7.9250     U        S  Miss   
3       1  female  35.0      1      0  53.1000     C        S   Mrs   
4       3    male  35.0      0      0   8.0500     U        S    Mr   

   FamilySize  Singleton  SmallFamily  LargeFamily  
0           2          0            1            0  
1           2          0            1            0  
2           1          1            0            0  
3           2          0            1            0  
4           1          1            0            0

In [22]:
# `Cabin` dummy encoding 
embarked_dummies = pd.get_dummies(combined_train_data['Cabin'], prefix='Cabin')
combined_train_data = pd.concat([combined_train_data, embarked_dummies], axis=1)
combined_train_data.drop('Cabin',axis=1,inplace=True)

In [23]:
# `Embarked` dummy encoding 
embarked_dummies = pd.get_dummies(combined_train_data['Embarked'], prefix='Embarked')
combined_train_data = pd.concat([combined_train_data, embarked_dummies], axis=1)
combined_train_data.drop('Embarked',axis=1,inplace=True)

In [24]:
# `Title` dummy encoding 
title_dummies = pd.get_dummies(combined_train_data['Title'], prefix='Title')
combined_train_data = pd.concat([combined_train_data, title_dummies], axis=1)
combined_train_data.drop('Title',axis=1,inplace=True)

In [25]:
combined_train_data['Sex'] = combined_train_data['Sex'].map({'male':1,'female':0})

In [26]:
#  对于 Pclass，只是个等级标记，所以也应该进行 dummy encoding 
# `Pclass` dummy encoding 
pclass_dummies = pd.get_dummies(combined_train_data['Pclass'], prefix='Pclass')
combined_train_data = pd.concat([combined_train_data, pclass_dummies], axis=1)
combined_train_data.drop('Pclass',axis=1,inplace=True)

In [27]:
combined_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 42 columns):
Sex               1309 non-null int64
Age               1309 non-null float64
SibSp             1309 non-null int64
Parch             1309 non-null int64
Fare              1309 non-null float64
FamilySize        1309 non-null int64
Singleton         1309 non-null int64
SmallFamily       1309 non-null int64
LargeFamily       1309 non-null int64
Cabin_A           1309 non-null uint8
Cabin_B           1309 non-null uint8
Cabin_C           1309 non-null uint8
Cabin_D           1309 non-null uint8
Cabin_E           1309 non-null uint8
Cabin_F           1309 non-null uint8
Cabin_G           1309 non-null uint8
Cabin_T           1309 non-null uint8
Cabin_U           1309 non-null uint8
Embarked_C        1309 non-null uint8
Embarked_Q        1309 non-null uint8
Embarked_S        1309 non-null uint8
Title_Capt        1309 non-null uint8
Title_Col         1309 non-null uint8
Title_Countess 

In [28]:
combined_train_data.shape

(1309, 42)

In [29]:
combined_train_data.head()

Sex   Age  SibSp  Parch     Fare  FamilySize  Singleton  SmallFamily  \
0    1  22.0      1      0   7.2500           2          0            1   
1    0  38.0      1      0  71.2833           2          0            1   
2    0  26.0      0      0   7.9250           1          1            0   
3    0  35.0      1      0  53.1000           2          0            1   
4    1  35.0      0      0   8.0500           1          1            0   

   LargeFamily  Cabin_A    ...     Title_Mme  Title_Mr  Title_Mrs  Title_Ms  \
0            0        0    ...             0         1          0         0   
1            0        0    ...             0         0          1         0   
2            0        0    ...             0         0          0         0   
3            0        0    ...             0         0          1         0   
4            0        0    ...             0         1          0         0   

   Title_None  Title_Rev  Title_Sir  Pclass_1  Pclass_2  Pclass_3  
0           0          0          0         0         0         1  
1           0          0          0         1         0         0  
2           0          0          0         0         0         1  
3           0          0          0         1         0         0  
4           0          0          0         0         0         1  

[5 rows x 42 columns]

In [30]:
# feature scale
from sklearn.preprocessing import MinMaxScaler

scaler_data = MinMaxScaler().fit_transform(combined_train_data[['Age','Fare', 'FamilySize']])
combined_train_data['Age'] = scaler_data[:, 0]
combined_train_data['Fare'] = scaler_data[:, 1]
combined_train_data['FamilySize'] = scaler_data[:, 2]
combined_train_data.head()

Sex       Age  SibSp  Parch      Fare  FamilySize  Singleton  SmallFamily  \
0    1  0.273456      1      0  0.014151         0.1          0            1   
1    0  0.473882      1      0  0.139136         0.1          0            1   
2    0  0.323563      0      0  0.015469         0.0          1            0   
3    0  0.436302      1      0  0.103644         0.1          0            1   
4    1  0.436302      0      0  0.015713         0.0          1            0   

   LargeFamily  Cabin_A    ...     Title_Mme  Title_Mr  Title_Mrs  Title_Ms  \
0            0        0    ...             0         1          0         0   
1            0        0    ...             0         0          1         0   
2            0        0    ...             0         0          0         0   
3            0        0    ...             0         0          1         0   
4            0        0    ...             0         1          0         0   

   Title_None  Title_Rev  Title_Sir  Pclass_1  Pclass_2  Pclass_3  
0           0          0          0         0         0         1  
1           0          0          0         1         0         0  
2           0          0          0         0         0         1  
3           0          0          0         1         0         0  
4           0          0          0         0         0         1  

[5 rows x 42 columns]

In [31]:
# 分割得到训练集和测试集
train_X = combined_train_data.ix[:890]
train_Y = train_data.Survived

test_X = combined_train_data.ix[891:]

In [32]:
train_X.shape, train_Y.shape, test_X.shape

((891, 42), (891,), (418, 42))

# Modeling

In [33]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
clf = ExtraTreesClassifier(n_estimators=100)
clf.fit(train_X, train_Y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [34]:
feature_importance = pd.DataFrame()
feature_importance['feature'] = train_X.columns
feature_importance['importance'] = clf.feature_importances_

feature_importance.sort(['importance'], ascending=False)

feature  importance
4             Fare    0.191627
1              Age    0.187963
33        Title_Mr    0.141111
0              Sex    0.100176
41        Pclass_3    0.040481
30      Title_Miss    0.039567
34       Title_Mrs    0.034940
39        Pclass_1    0.025088
17         Cabin_U    0.024739
7      SmallFamily    0.022631
5       FamilySize    0.021434
2            SibSp    0.019884
8      LargeFamily    0.018001
29    Title_Master    0.014572
3            Parch    0.014285
40        Pclass_2    0.014257
20      Embarked_S    0.012869
13         Cabin_E    0.011476
18      Embarked_C    0.010742
6        Singleton    0.010400
19      Embarked_Q    0.007472
10         Cabin_B    0.006477
11         Cabin_C    0.006121
12         Cabin_D    0.005920
37       Title_Rev    0.004912
25        Title_Dr    0.002412
9          Cabin_A    0.002171
14         Cabin_F    0.001688
15         Cabin_G    0.001197
21      Title_Capt    0.001048
22       Title_Col    0.000903
28     Title_Major    0.000691
24       Title_Don    0.000647
26  Title_Jonkheer    0.000551
35        Title_Ms    0.000443
16         Cabin_T    0.000411
38       Title_Sir    0.000327
31      Title_Mlle    0.000140
23  Title_Countess    0.000118
27      Title_Lady    0.000057
32       Title_Mme    0.000053
36      Title_None    0.000000

In [35]:
selectModel = SelectFromModel(clf, prefit=True, threshold=0.013763)
train_X_new = selectModel.transform(train_X)
test_X_new = selectModel.transform(test_X)

In [36]:
train_X_new.shape, test_X_new.shape

((891, 16), (418, 16))

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import StratifiedKFold
from sklearn.grid_search import GridSearchCV

# 随机森林模型的超参数选择
forest = RandomForestClassifier()

forest_parameter_grid = {
                 'max_depth' : [3,4,5,6,7,8,9],
                 'n_estimators': [60, 80, 100,140,180,200,240],
                 'criterion': ['gini','entropy']
                 }

cross_validation = StratifiedKFold(train_Y, n_folds=5)

forest_grid_search = GridSearchCV(forest,
                           param_grid=forest_parameter_grid,
                           cv=cross_validation)

forest_grid_search.fit(train_X_new, train_Y)

print('Best score: {}'.format(forest_grid_search.best_score_))
print('Best parameters: {}'.format(forest_grid_search.best_params_))

/home/sunnymarkliu/software/miniconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/sunnymarkliu/software/miniconda2/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


Best score: 0.833894500561
Best parameters: {'n_estimators': 180, 'criterion': 'gini', 'max_depth': 3}


In [46]:
# GradientBoostingClassifier 模型的超参数选择
from sklearn.ensemble import GradientBoostingClassifier

gbc_parameter_grid = {
                 'learning_rate' : [0.001, 0.003, 0.009, 0.025, 0.075, 0.1, 0.3, 0.6, 0.8, 1, 1.2],
                 'max_depth' : [3,4,5,6,7,8],
                 'n_estimators': [100,140,180,200,240,280,300, 320],
                 'max_features' : ['sqrt','log2', None]
                 }

gbc = GradientBoostingClassifier()
gbc_grid_search = GridSearchCV(gbc,
                           param_grid=gbc_parameter_grid,
                           cv=cross_validation)

gbc_grid_search.fit(train_X_new, train_Y)

print('gbc Best score: {}'.format(gbc_grid_search.best_score_))
print('gbc Best parameters: {}'.format(gbc_grid_search.best_params_))

gbc Best score: 0.847362514029
gbc Best parameters: {'max_features': None, 'n_estimators': 200, 'learning_rate': 0.075, 'max_depth': 4}


In [47]:
# XGBClassifier 模型的超参数选择
from xgboost import XGBClassifier

xgbc_parameter_grid = {
                 'learning_rate' : [0.001, 0.003, 0.009, 0.025, 0.075, 0.1, 0.3, 0.6, 0.8, 1, 1.2],
                 'max_depth' : [2,3,4,5,6,7,8,9,10],
                 'n_estimators': [100,140,180,200,240,280,320],
                 }

xgbc = XGBClassifier()
xgbc_grid_search = GridSearchCV(xgbc,
                           param_grid=xgbc_parameter_grid,
                           cv=cross_validation)

xgbc_grid_search.fit(train_X_new, train_Y)

print('xgbc Best score: {}'.format(xgbc_grid_search.best_score_))
print('xgbc Best parameters: {}'.format(xgbc_grid_search.best_params_))

xgbc Best score: 0.845117845118
xgbc Best parameters: {'n_estimators': 320, 'learning_rate': 0.075, 'max_depth': 3}


In [48]:
# LogisticRegression 模型的超参数选择
from sklearn.linear_model import LogisticRegression

logistic_parameter_grid = {
                 'C' : [0.1,0.2,0.4, 0.8,1,1.5,2,4,6,8,10],
                 'max_iter': [50, 80, 100,120,140,160,180,200,220,240,260,280,300]
                 }

logistic = LogisticRegression()
logistic_grid_search = GridSearchCV(logistic,
                           param_grid=logistic_parameter_grid,
                           cv=cross_validation)

logistic_grid_search.fit(train_X_new, train_Y)

print('logistic Best score: {}'.format(logistic_grid_search.best_score_))
print('logistic Best parameters: {}'.format(logistic_grid_search.best_params_))

logistic Best score: 0.83164983165
logistic Best parameters: {'C': 1, 'max_iter': 50}


In [49]:
# AdaBoostClassifier 模型的超参数选择
from sklearn.ensemble import AdaBoostClassifier

adaboost_parameter_grid = {
                 'learning_rate' : [0.001, 0.025, 0.075, 0.1, 0.3, 0.6, 0.8, 1, 1.2],
                 'n_estimators': [50,80,100,120,140,160,180,200,220,240,260,280]
                 }

adaboost = AdaBoostClassifier()
adaboost_grid_search = GridSearchCV(adaboost,
                           param_grid=adaboost_parameter_grid,
                           cv=cross_validation)

adaboost_grid_search.fit(train_X_new, train_Y)

print('adaboost Best score: {}'.format(adaboost_grid_search.best_score_))
print('adaboost Best parameters: {}'.format(adaboost_grid_search.best_params_))

adaboost Best score: 0.828282828283
adaboost Best parameters: {'n_estimators': 140, 'learning_rate': 0.1}


** GridSearch 获取的最佳模型参数如下：**
1. RandomForestClassifier
```
Best score: 0.833894500561
Best parameters: {'n_estimators': 180, 'criterion': 'gini', 'max_depth': 3}
```

2. GradientBoostingClassifier
```
Best score: 0.847362514029
Best parameters: {'max_features': None, 'n_estimators': 200, 'learning_rate': 0.075, 'max_depth': 4}
```

3. XGBClassifier
```
Best score: 0.845117845118
Best parameters: {'n_estimators': 320, 'learning_rate': 0.075, 'max_depth': 3}
```

4. LogisticRegression
```
Best score: 0.83164983165
Best parameters: {'C': 1, 'max_iter': 50}
```

5. AdaBoostClassifier
```
Best score: 0.828282828283
Best parameters: {'n_estimators': 140, 'learning_rate': 0.1}
```

In [50]:
# best params model
forest = RandomForestClassifier(n_estimators=180, criterion='gini', max_depth=3)
gradientBoosting = GradientBoostingClassifier(max_features=None, n_estimators=200, learning_rate=0.075,
                                              max_depth=4)
xgb = XGBClassifier(n_estimators=320, learning_rate=0.075, max_depth=3)
logistic = LogisticRegression(C=1, max_iter=50)
adaBoost = AdaBoostClassifier(n_estimators=140, learning_rate=0.1)

In [51]:
# ensemble and voting predict
from sklearn.ensemble import VotingClassifier

voting = VotingClassifier(estimators=[
        ('forest', forest), ('gradientBoosting', gradientBoosting), 
        ('xgb', xgb), ('logistic', logistic), 
        ('adaBoost', adaBoost)], voting='soft')

voting = voting.fit(train_X_new, train_Y)
predictions = voting.predict(test_X_new)

In [53]:
submission = pd.DataFrame({
        "PassengerId": test_data['PassengerId'],
        "Survived": predictions
    })

submission.to_csv("result/advance_voting_predictions_1_31.csv", index=False)
print 'Done'

Done


In [60]:
xgb_predictions = xgbc_grid_search.predict(test_X_new).astype(int)
submission = pd.DataFrame({
        "PassengerId": test_data['PassengerId'],
        "Survived": xgb_predictions
    })

submission.to_csv("result/advance_xgbc_grid_search_predictions_1_31.csv", index=False)

In [62]:
gbc_predictions = gbc_grid_search.predict(test_X_new).astype(int)
submission = pd.DataFrame({
        "PassengerId": test_data['PassengerId'],
        "Survived": gbc_predictions
    })

submission.to_csv("result/advance_gbc_grid_search_predictions_1_31.csv", index=False)

In [57]:
adaboost_predictions = adaboost_grid_search.predict(test_X_new).astype(int)
submission = pd.DataFrame({
        "PassengerId": test_data['PassengerId'],
        "Survived": adaboost_predictions
    })

submission.to_csv("result/advance_adaboost_grid_search_predictions_1_31.csv", index=False)

In [56]:
logistic_predictions = logistic_grid_search.predict(test_X_new).astype(int)
submission = pd.DataFrame({
        "PassengerId": test_data['PassengerId'],
        "Survived": logistic_predictions
    })

submission.to_csv("result/advance_logistic_grid_search_predictions_1_31.csv", index=False)

In [55]:
forest_predictions = forest_grid_search.predict(test_X_new).astype(int)
submission = pd.DataFrame({
        "PassengerId": test_data['PassengerId'],
        "Survived": forest_predictions
    })

submission.to_csv("result/advance_forest_grid_search_predictions_1_31.csv", index=False)